app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path("__debug__/", include("debug_toolbar.urls")),
        
]

app/users/urls.py
from django.urls import path, include
from users.views import (
    IndexView, RegistrationUserView, LoginUserView, DetailUserView, DeleteUserView, LogoutUserView, ProfileUserView,
    UserPasswordChangeView, UserPasswordChangeDoneView, UserPasswordResetView, EmailVerificationView
    , UserPasswordResetDoneView, 
    UserPasswordResetConfirmView, UserPasswordResetCompleteView
    )

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('<uuid:id>/profile/', ProfileUserView.as_view(), name='profile'),
    path('<id>/delete/', DeleteUserView.as_view(), name='delete'),
    path('<id>/', DetailUserView.as_view(), name='info'),

    path('register', RegistrationUserView.as_view(), name='register'),
    path('login', LoginUserView.as_view(), name='login'),
    path('logout', LogoutUserView.as_view(), name='logout'),
    
    path('password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('password_change_done', UserPasswordChangeDoneView.as_view(), name='password_change_done'),
    
    path('password_reset/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    
    path('verify/<str:email>/<code>/', EmailVerificationView.as_view(), name='email_verification'),
]

app/users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import now

class Person(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    is_verified_email = models.BooleanField(default=False)
    
class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=Person, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()
    
    def send_verification_mail(self):        
        link = reverse('users:email_verification', kwargs={'email':self.user.email, 'code':self.code} )
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        print(verification_link)
        subject = "Подтверждение Регистрации"
        message = f"для подтверждения перейдите по ссылке: {verification_link}"
        from_email=settings.EMAIL_HOST_USER
        recipient_list=[self.user.email]
        print(settings)
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=recipient_list,
            fail_silently=False,
        )
        
    def is_expired(self):
        return True if now() >= self.expiration else False

app/users/forms.py
from typing import Any
from datetime import timedelta
from django import forms
from users.models import Person
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, SetPasswordForm
# from django.forms import 
from django.core.mail import send_mail
from users.models import EmailVerification
from django.utils.timezone import now

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder':'Введите имя'
        }
    ),label=False)
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'placeholder':'mail@gmail.com'
        }
    ),label=False)
    class Meta:
        model = Person
        fields = ['username','email']

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder':'Введите имя'
        }
    ),label=False)
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder':'Супер пароль'
        }
    ),label=False)
    class Meta:
        model = Person
        
#         fields = ['username','password']
        
class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder':'Андрей'
        }
    ),label=False)
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'placeholder':'mail@gmail.com'
        }
    ),label=False)
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder':'Супер пароль'
        }
    ),label=False)
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder':'Повтор Супер пароля'
        }
    ),label=False)
    
    class Meta:
        model = Person
        fields = ['username','email','password1','password2']
        

    def save(self, commit: bool = True):
        user = super().save(commit)
        expiration = now() + timedelta(hours=24)
        record = EmailVerification.objects.create(
            code=user.id,
            user=user,
            expiration=expiration
        )
        record.send_verification_mail()
        return user

class UserSetPasswordForm(SetPasswordForm):

    class Meta:
        model = Person

app/users/views.py
from typing import Any
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse, HttpResponse as HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.forms import PasswordResetForm
from django.contrib import auth, messages
from django.urls import reverse, reverse_lazy
from users.models import Person, EmailVerification
from users.forms import UserLoginForm, UserRegistrationForm, ProfileUserForm, UserSetPasswordForm
from django.contrib.auth import logout
from django.shortcuts import redirect
from .mixins import BtnTitleMixin
from django.contrib.auth.hashers import make_password


# Create your views here.
class IndexView(ListView):
    template_name = 'index.html'
    model = Person
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['current_user'] = self.request.user
        context['current_user_id'] = self.request.user.id
        
        context['users'] = Person.objects.all().order_by('username')
        return context

class DetailUserView(DetailView):
    model = Person
    template_name = 'user_detail.html'
    
    def get_object(self, queryset=None):
        return Person.objects.get(id=self.kwargs.get("id"))

class ProfileUserView(UpdateView):
    model = Person
    template_name = 'user_edit.html'
    form_class = ProfileUserForm
    success_url = reverse_lazy('users:index')
    # btn_title = 
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        context['btn_title'] = "Изменить пользователя"
        return context
    
    def get_object(self, queryset=None):
        
        return Person.objects.get(id=self.kwargs.get("id"))
    
    

class DeleteUserView(BtnTitleMixin, DeleteView):
    model = Person
    template_name = 'user_delete.html'
    btn_title = "Удалить пользователя"
    
    def get_object(self, queryset=None):
        return Person.objects.get(id=self.kwargs.get("id"))
    
    success_url = reverse_lazy('users:index')

class LoginUserView(BtnTitleMixin, LoginView):
    model = Person
    template_name = 'user_login.html'
    form_class = UserLoginForm
    btn_title = "Войти"
    redirect_authenticated_user = True

    def get_redirect_url(self):
        return reverse_lazy('users:index')


class LogoutUserView(LogoutView):
    model = Person
    http_method_names = ['get']
    
    def get(self, request: HttpRequest) -> HttpResponse:
        logout(request=request)
        return redirect('users:index')
    

class RegistrationUserView(BtnTitleMixin, CreateView):
    model = Person
    template_name = 'user_register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')
    btn_title = "Зарегистрироваться"
    
    
class UserPasswordChangeView(BtnTitleMixin, PasswordChangeView):
    model = Person
    template_name = 'user_password_change.html'
    success_url = reverse_lazy("users:password_change_done")
    btn_title = "Изменить пароль"
    
    
class UserPasswordResetView(BtnTitleMixin, PasswordResetView):
    model = Person
    template_name = 'user_password_reset.html'
    email_template_name = "password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    btn_title = "Сбросить пароль"
    

class UserPasswordChangeDoneView(PasswordResetDoneView):
    model = Person
    template_name = 'password_change_done.html'
    
class EmailVerificationView(TemplateView):
    template_name = "email_verification.html"
    
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any):
        code = kwargs['code']
        user = Person.objects.get(email=kwargs['email'])
        email_verification = EmailVerification.objects.filter(user=user, code=code)
        if email_verification and email_verification.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('users:index'))
        
class UserPasswordResetDoneView(PasswordResetDoneView):    
    template_name = 'password_reset_done.html'

    
    
class UserPasswordResetConfirmView(BtnTitleMixin,PasswordResetConfirmView):
    template_name = 'user_password_reset.html'
    success_url = reverse_lazy("users:password_reset_complete")
    form_class=UserSetPasswordForm
    btn_title = "Сменить Пароль"
    
class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "password_reset_complete.html"

app/users/templates/email_verification.html
<p>Поздравляю!</p>

<p>Ваша учетная запись успешно подтверждена!</p>

app/users/templates/index.html
{% if current_user.is_authenticated %}
<a href="{% url 'users:profile' current_user.id %}">{{current_user.username}}</a>
{% endif %}
<hr>
{% for user in  users%}
    <li>
        <a href="{% url 'users:info' user.id %}">{{user.username}}</a> 
        {% if current_user.is_staff or current_user.is_superuser %}
            | <a href="{% url 'users:profile' user.id %}">profile</a>
            | <a href="{% url 'users:delete' user.id %}">delete</a></li>
        {% endif %}
{% endfor %}
<hr>
{% if not current_user.is_authenticated %}
    <a href="{% url 'users:login' %}"> Вход</a>
    | <a href="{% url 'users:register' %}"> Регистрация</a>
    {% else %}
    <a href="{% url 'users:logout' %}"> Выход</a>
{% endif %}

app/users/templates/password_change_done.html
пароль успешно изменен
<hr>
<a href="{% url 'users:profile' request.user.id %}"> Вернуться в профиль</a>

app/users/templates/password_reset_complete.html
Пароль успешно изменен

app/users/templates/password_reset_done.html
<p>Был запрос смены пароля</p>
<hr>
<p>На почту были отправлены инструкции для дальнейших действий</p>

app/users/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
 
{% endautoescape %}

app/users/templates/user_delete.html
<p>{{ object.id }}</p>
<p>{{ object.username }}</p>
Удалить?
<form  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ btn_title }}">
</form>

app/users/templates/user_detail.html
<p>{{ object.id }}</p>
<p>{{ object.username }}</p>
<p>{{ object.email }}</p>
<hr>
<a href="{% url 'users:index'  %}">К списку пользователей</a>

app/users/templates/user_edit.html
<form  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ btn_title }}">
</form>

<a href="{% url 'users:password_change'  %}">Сменить пароль</a> | <a href="{% url 'users:index'  %}">К списку пользователей</a>

app/users/templates/user_login.html
login
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="{{ btn_title }}">
</form>

<a href="{% url 'users:password_reset'  %}">Сбросить пароль</a>

app/users/templates/user_logout.html
sss

app/users/templates/user_password_change.html
<form  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ btn_title }}">
</form>

app/users/templates/user_password_reset.html
<form  method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ btn_title }}">
</form>

app/users/templates/user_register.html
rega
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{{ btn_title }}">
</form>